### ISSUE TITLE
smart truncate

### ISSUE THREAD

**Issue by ComLock** [bvaughn/highlight-words-core#13]
So this can become rather complicated, and I have not thought this quite through yet, but here we go:

I would like a truncate functionality that limits the length of the highlighted text.
It should be able to replace the start, the end or both with a custom ellipsis.
It should find the index of the first highlight and perhaps allow for a custom number of letters or words to be present before the highlighted word. I guess knowing what is a word becomes a problem of language so number of letters should be a sufficient starting point.

It should not insert ellipsis if the string is short enough.

I needs to do all that before applying html elements like for instance bold.

I could not find any npm module for this. And due to its complexity I figure it needs to be part of the highlighter.

**Comment by ComLock** [comment]
If all the highlighted terms are towards the end of the string it should still try to fill the truncated text to its limit.

**Comment by bvaughn** [comment]
What you're describing sounds pretty specific. This package is meant to be more of a generic solution.

You'd be welcome to implement what you're describing above as a PR for consideration but I don't have the time to add such a feature to this package, or the need for it. 😄

Going to close this issue (since I don't plan on taking any action on it) but we can keep talking here after it's closed!

**Comment by ComLock** [comment]
This only does end truncation but worth a mention https://github.com/alexghr/html-ellipsis

**Comment by ComLock** [comment]
This might be what I'm looking for https://www.npmjs.com/package/highlight-search-result

**Comment by ComLock** [comment]
Yup that works. Made a PR too. https://github.com/dominictarr/highlight-search-result/pull/4
I'm done for now.

**Comment by bvaughn** [comment]
Cool! Glad you found something that works for you :)
